### ISSUE TITLE
'IndexOf' Error

### ISSUE THREAD

**Issue by GeorgeDziov** [anyuser/vectorshapes-unity#3]
If this project is still worked on, here's an issue I got in a fresh 2019.4.18f1 project (downloaded this project as a zip)

Assets\Editor\ShapeEditorUtils.cs(30,36): error CS1061: 'NativeArray<int>' does not contain a definition for 'IndexOf' and no accessible extension method 'IndexOf' accepting a first argument of type 'NativeArray<int>' could be found (are you missing a using directive or an assembly reference?)

There are three errors total - (30,36), (37,37) and (43,36)

**Comment by anyuser** [comment]
In case that's still relevant, the last version in the main branch is not compatible with 2019.4 anymore, use the unity_2019 branch instead (add ```https://github.com/anyuser/vectorshapes-unity.git#unity_2019``` as package url). There are also other branches for each major unity version.
