### ISSUE TITLE
Problem with shader application

### ISSUE THREAD

**Issue by PXLcat** [anyuser/vectorshapes-unity#4]
Hi! I herited a project using vectorshape, and so far we have been using a shader that repeated on the shape we generated : 
![](https://cdn.discordapp.com/attachments/771308433646682118/968420757661155338/unknown.png)
Thing is, we wanted to try another shader (using ShaderGraph), but this is what happens :
![image](https://user-images.githubusercontent.com/35851077/165251902-20ae37cf-abc6-490b-9aba-9891a63a3a51.png)
Whatever the shape is (and the parameters I choose), it seems to only apply on a 1*1 square.
![image](https://user-images.githubusercontent.com/35851077/165252453-13f83bc4-ad82-4bfc-933d-d40b06ac03f1.png)

Is this something that other users had and can be fixed? I apologize if the problem comes from something else.

**Comment by anyuser** [comment]
Should be fixed now, I accidentally broke the tiling functionality when updating the shader to support linear color space.
